version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 main:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tradingbot
      - SECRET_KEY=development_key
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tradingbot
    ports:
      - "5432:5432"

volumes:
  postgres_data: